### PR TITLE
Support Blacklight 7

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
@mejackreed can you make a `blacklight/gallery.svg` for us?  The remaining 3 tests are failing because we don't have one.

**Comment by mejackreed** [comment]
Yep. On it.

**Comment by no-reply** [comment]
Would it be possible to get a status update on this?

It blocks `hyrax` testing on Blacklight 7 right now and it's not immediately clear to me what I can do to help push it forward.

**Comment by jcoyne** [comment]
Status update is that nobody has looked at this for a year.  It's not know as to why that one test is failing.

**Comment by dgcliff** [comment]
@camillevilla Would it be possible to cut a new release of blacklight-gallery? It'd be nice to have the blacklight 7 support in a gem.

**Comment by camillevilla** [comment]
@dgcliff Thanks for reaching out. We'll have a few of the maintainers together at the code4lib conf next week, so I'm optimistic about cutting a release in the next week or so.

**Pull request merged**
